### ISSUE TITLE
transmitting message from minecraft causes infinite server error logging

### ISSUE THREAD

**Issue by jasperfirecai2** [NikkyAI/MatterLinkApi#1]
Hi,

A friend and I have tried to set up a matterlink and bridge but we've currently run into this issue whenever we type something in minecraft:
```
[21:09:59] [Server thread/INFO] [STDERR]: [matterlink.api.MessageHandler:transmitMessage:161]:  at matterlink.api.MessageHandler.transmitMessage(MessageHandler.java:166)
[21:09:59] [Server thread/INFO] [STDERR]: [matterlink.api.MessageHandler:transmitMessage:161]:  at matterlink.api.MessageHandler.transmit(MessageHandler.java:119)
[21:09:59] [Server thread/INFO] [STDERR]: [matterlink.api.MessageHandler:transmitMessage:161]:  at matterlink.api.MessageHandler.stop(MessageHandler.java:61)
```

these three lines keep repeating themselves and time everyone out from the server. What other info do you need from me to help resolve this?

**Comment by NikkyAI** [comment]
found the issue (most likely)

fixed in 063ad04b24623b28a2850eb1543ae07a2608e87a
